---
title: "Simple R Markdown Notebook"
author: "Lincoln Mullen"
---

### What is this?

This is a 'fork' - a copy - of Lincoln Mullen's 'Simple R Markdown Notebook'. [R Markdown](http://rmarkdown.rstudio.com/) is like 'ordinary' Markdown with the added benefit of being able to run and display R code you use for your analysis. In this version of Mullen's notebook, we've added code to support the [hypothes.is](http://hypothes.is) web annotation framework. That way, not only can you share your notes, your code, and your results, but others can annotate and share their annotations! 

When you run the 'make' command from the command line, your notecards - your .Rmd files - get transformed into a nice looking HTML site. In this way, we move from research to publication in an easy manner.

The snippet of code below shows how the table of contents for rendered versions of every R Markdown document in this repository is generated.

### Table of contents

```{r echo=FALSE, results='asis'}
rmd <- Sys.glob("*.Rmd")
rmd <- rmd[rmd != "index.Rmd"]
html <- sub(".Rmd", ".html", rmd)
lines <- lapply(rmd, readLines)
yaml <- lapply(lines, rmarkdown:::parse_yaml_front_matter)
cat("<ul>")
for (i in seq_along(rmd)) {
  cat(paste0("<li><a href='", html[i], "'>", yaml[[i]]$title, "</a><br/>",
             "<code>", rmd[i], "</code>", "</li>"))
}
cat("</ul>")
```

### What does this do?

As little as possible. The aim is to be very lightweight. But it does do this:

1. Includes an index page (you're looking at it) with a table of contents for every `.Rmd` file in the root directory of your project.
2. Inserts a navigation header into each rendered HTML file.
4. Sets some shared options for HTML documents rendered from R Markdown.
5. Contains a basic Makefile to render all the documents.
  
If you want to get fancy, you can add these two lines to the `[remote "origin"]` section of your `.git/config` file, so that any `git push` command will push to both the `master` and the `gh-pages` branch. Or you can just rename `master` to `gh-pages`. (This tip from [Brett Terpstra](http://brettterpstra.com/2012/09/26/github-tip-easily-sync-your-master-to-github-pages/), who gives more details.)

```
push = +refs/heads/master:refs/heads/gh-pages
push = +refs/heads/master:refs/heads/master
```

Don't forget to commit the HTML files that you generate.

See the [GitHub repository](https://github.com/lmullen/rmd-notebook) for the original source. See the [R Markdown documentation](http://rmarkdown.rstudio.com/) if you want to do more.
